///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CopyFunctionality
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CopyFunctionalityRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("1d7b296a-f5ba-4566-83f3-76a9778b117f")]
    public partial class CopyFunctionalityRepository : RepoGenBaseFolder
    {
        static CopyFunctionalityRepository instance = new CopyFunctionalityRepository();
        CopyFunctionalityRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        CopyFunctionalityRepositoryFolders.SnapXCopyMxyAppFolder _snapxcopymxy;
        CopyFunctionalityRepositoryFolders.InspectionAppFolder _inspection;

        /// <summary>
        /// Gets the singleton class instance representing the CopyFunctionalityRepository element repository.
        /// </summary>
        [RepositoryFolder("1d7b296a-f5ba-4566-83f3-76a9778b117f")]
        public static CopyFunctionalityRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CopyFunctionalityRepository() 
            : base("CopyFunctionalityRepository", "/", null, 0, false, "1d7b296a-f5ba-4566-83f3-76a9778b117f", ".\\RepositoryImages\\CopyFunctionalityRepository1d7b296a.rximgres")
        {
            _snapxuntitled = new CopyFunctionalityRepositoryFolders.SnapXUntitledAppFolder(this);
            _snapxcopymxy = new CopyFunctionalityRepositoryFolders.SnapXCopyMxyAppFolder(this);
            _inspection = new CopyFunctionalityRepositoryFolders.InspectionAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1d7b296a-f5ba-4566-83f3-76a9778b117f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("f0c58a38-6ec1-492c-833c-f5a031cf6d61")]
        public virtual CopyFunctionalityRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The SnapXCopyMxy folder.
        /// </summary>
        [RepositoryFolder("99e8b054-6b73-4ca1-a9a5-14e617bf18cf")]
        public virtual CopyFunctionalityRepositoryFolders.SnapXCopyMxyAppFolder SnapXCopyMxy
        {
            get { return _snapxcopymxy; }
        }

        /// <summary>
        /// The Inspection folder.
        /// </summary>
        [RepositoryFolder("3ded2e50-5a8f-425d-93e3-bf20b38e67c3")]
        public virtual CopyFunctionalityRepositoryFolders.InspectionAppFolder Inspection
        {
            get { return _inspection; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class CopyFunctionalityRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0c58a38-6ec1-492c-833c-f5a031cf6d61")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "f0c58a38-6ec1-492c-833c-f5a031cf6d61", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "121933c6-21c3-4e58-88dc-b46ddc9b99ba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0c58a38-6ec1-492c-833c-f5a031cf6d61")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0c58a38-6ec1-492c-833c-f5a031cf6d61")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("121933c6-21c3-4e58-88dc-b46ddc9b99ba")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("121933c6-21c3-4e58-88dc-b46ddc9b99ba")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

        /// <summary>
        /// The SnapXCopyMxyAppFolder folder.
        /// </summary>
        [RepositoryFolder("99e8b054-6b73-4ca1-a9a5-14e617bf18cf")]
        public partial class SnapXCopyMxyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _finishInfo;
            RepoItemInfo _bigtoffwInfo;
            RepoItemInfo _ffwtobigInfo;

            /// <summary>
            /// Creates a new SnapXCopyMxy  folder.
            /// </summary>
            public SnapXCopyMxyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXCopyMxy", "/form[@title='Snap-X - [Copy.mxy]']", parentFolder, 30000, null, true, "99e8b054-6b73-4ca1-a9a5-14e617bf18cf", "")
            {
                _finishInfo = new RepoItemInfo(this, "Finish", "container[@controlid='59648']/form[@controlid='65281']/?/?/element[@controlid='59649']/element[@controlid='59648']/?/?/button[@text='Finish' and @enabled='True']", 600000, null, "b64cbcbb-ae1c-4265-97c4-99583cf1579a");
                _bigtoffwInfo = new RepoItemInfo(this, "BIGtoFFW", "?/?/form[@controlid='65281']//container[@controlid='59648']/toolbar[@class='ToolbarWindow32' and @instance='7']/button[@commandid='40028']", 30000, null, "bd8578b7-5986-4974-97f0-002f024276f6");
                _ffwtobigInfo = new RepoItemInfo(this, "FFWtoBIG", "container[@controlid='59648']/form[@controlid='65280']/?/?/element[@controlid='59650']/element[@controlid='59648']/toolbar[@controlid='59392']/button[@commandid='40029']", 30000, null, "7f7bd033-7d4b-48ea-9d0a-170c13673bcd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("99e8b054-6b73-4ca1-a9a5-14e617bf18cf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("99e8b054-6b73-4ca1-a9a5-14e617bf18cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("b64cbcbb-ae1c-4265-97c4-99583cf1579a")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("b64cbcbb-ae1c-4265-97c4-99583cf1579a")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The BIGtoFFW item.
            /// </summary>
            [RepositoryItem("bd8578b7-5986-4974-97f0-002f024276f6")]
            public virtual Ranorex.Button BIGtoFFW
            {
                get
                {
                    return _bigtoffwInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BIGtoFFW item info.
            /// </summary>
            [RepositoryItemInfo("bd8578b7-5986-4974-97f0-002f024276f6")]
            public virtual RepoItemInfo BIGtoFFWInfo
            {
                get
                {
                    return _bigtoffwInfo;
                }
            }

            /// <summary>
            /// The FFWtoBIG item.
            /// </summary>
            [RepositoryItem("7f7bd033-7d4b-48ea-9d0a-170c13673bcd")]
            public virtual Ranorex.Button FFWtoBIG
            {
                get
                {
                    return _ffwtobigInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FFWtoBIG item info.
            /// </summary>
            [RepositoryItemInfo("7f7bd033-7d4b-48ea-9d0a-170c13673bcd")]
            public virtual RepoItemInfo FFWtoBIGInfo
            {
                get
                {
                    return _ffwtobigInfo;
                }
            }
        }

        /// <summary>
        /// The InspectionAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ded2e50-5a8f-425d-93e3-bf20b38e67c3")]
        public partial class InspectionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Inspection  folder.
            /// </summary>
            public InspectionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Inspection", "/form[@title='Inspection']", parentFolder, 30000, null, true, "3ded2e50-5a8f-425d-93e3-bf20b38e67c3", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='&OK' and @enabled='True']", 600000, null, "f3c8ff48-4163-4ddc-aba4-b0957b559081");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ded2e50-5a8f-425d-93e3-bf20b38e67c3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ded2e50-5a8f-425d-93e3-bf20b38e67c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("f3c8ff48-4163-4ddc-aba4-b0957b559081")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("f3c8ff48-4163-4ddc-aba4-b0957b559081")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}