///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CopyFunctionality
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            //string strActualValues = "D:\\Joro\\GIT_Automations\\AutomationCopy\\Reports\\ActualValuesBIG.STA";       //with the folowing 4 lines on this code we finding (we have the path) and reading into these files (ActualVAlues.STA and hardcodedVAlues.STA)
            //string strHardcodedValues = "D:\\Joro\\GIT_Automations\\AutomationCopy\\Reports\\HardcodedValuesBIG.STA";

            //string[] readActualLines = File.ReadAllLines(strActualValues);
            //string[] readHardcodedLines = File.ReadAllLines(strHardcodedValues);
        }

    }
}
